### ISSUE TITLE
Input raw unit conversion

### ISSUE THREAD

**Issue by DVDJMRTNZ** [cse442-fall-2019-offering/442projects-goose#15]
Figuring out the different possible conversions and how the conversion will occur in the app

**Comment by DVDJMRTNZ** [comment]
Distance based conversions will be converted to meters from the first selected unit, than converted from meters to the second selected unit. this is to ensure that in the future, more units can be added only needing a conversion to and from meters as opposed to needing a conversion ration for every unit already in the code, making the code cleaner and having a negligible change in run-time (still done in O(1))

**Comment by dlepine** [comment]
Task Test:
(1) Open conversion application
(2) Click on text fields
(3) Type in raw input to be converted
(4) View Results
