### ISSUE TITLE
I am from Europe and visiting America and I am unfamiliar with Fahrenheit and want to see how the Fahrenheit scale relates to Celcius so I select Temperature and pick Fahrenheit and Celcius as my units to compare them

### ISSUE THREAD

**Issue by EdwinChiu** [cse442-fall-2019-offering/442projects-goose#8]

**Comment by wedyer** [comment]
1) open conversion site
2) select temperature from nav bar
3) enter a unit to convert from
4) choose the unit type to convert from
5) choose a unit type to convert to
6) click convert
7) see visualization below
